services:
  redis:
    build:
      context: .
      dockerfile: ./redis/Dockerfile
      target: redis_base
    container_name: service-redis
    volumes:
      - redis_data:/var/lib/redis
      - redis_socket:/var/run/redis
    networks:
      - service-network

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
      target: php_prod
    container_name: service-php
    depends_on:
      - redis
    volumes:
      - ./src:/var/www/html/app
      - ./php/php.ini-production:/usr/local/etc/php/php.ini:ro
      - php_socket:/var/run/php
      - redis_socket:/var/run/redis
    env_file:
      - ./php/.env
    networks:
      - service-network

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: service-nginx
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html/app
      - php_socket:/var/run/php
    networks:
      - service-network

networks:
  service-network:
    driver: bridge

volumes:
  php_socket:
  redis_data:
    driver: local
  redis_socket:
